development:
  adapter: postgresql
  encoding: UTF8
  database: jobportal_development
  username: postgres
  password: postgres
  host: localhost
  pool: 5

# Note: using sqlite3 for development because I don't know how to use multiple
# postgres databases at the moment. rct 2015.10.07

test:
  adapter: postgresql
  encoding: unicode
  database: jobportal_test
  pool: 20
  username: postgres
  password: postgres
  host: localhost
  port: 5432

#test:
#  adapter: sqlite3
#  database: db/test<%= ENV['TEST_ENV_NUMBER'] %>.sqlite3
#  pool: 5
#  timeout: 5000

production:
  database: jobportal_production
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: postgres
  pool: 5